name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  map_view:

dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true
  assets:
    - assets/eletrico.png
    - assets/borracharia.png
    - assets/estofado.png
    - assets/lataria.png
    - assets/lavagem.png
    - assets/mecanico.png
    - assets/motor.png
    - assets/resolver.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf